# fly.toml app configuration file generated for finviz-api on 2025-03-22T23:36:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "finviz-api"
primary_region = "mad"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
